from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = DATA_DIR / "models"

MODEL_FILE = MODELS_DIR / "trained_model.json"
MOVE_SCORE_DATASET_FILE = MODELS_DIR / "move_score_dataset.json"
NEURAL_MODEL_FILE = MODELS_DIR / "neural_model.json"

TEST_FILE = PROJECT_ROOT / "tests" / "run_tests.py"

# Ancien modèle tabulaire.
TRAINING_GAMES_COUNT = 300
SIMULATIONS_PER_MOVE = 30
EVALUATION_GAMES_COUNT = 200

# Dataset Monte-Carlo destiné au moteur neuronal.
MOVE_SCORE_DATASET_MAX_EXAMPLES = 1000

# Modèle neuronal sauvegardé.
NEURAL_TRAINING_GAMES_COUNT = 1000
NEURAL_SIMULATIONS_PER_MOVE = 30
NEURAL_MAX_EXAMPLES = 1000
NEURAL_TACTICAL_REPEAT_COUNT = 25
NEURAL_HIDDEN_SIZE = 18
NEURAL_EPOCHS = 240
NEURAL_LEARNING_RATE = 0.04
NEURAL_EVALUATION_GAMES_COUNT = 200

# Benchmark / entraînement surveillé.
NEURAL_BENCHMARK_TRAINING_GAMES_COUNT = 1000
NEURAL_BENCHMARK_SIMULATIONS_PER_MOVE = 30
NEURAL_BENCHMARK_MAX_EXAMPLES = 1000
NEURAL_BENCHMARK_TACTICAL_REPEAT_COUNT = 50
NEURAL_BENCHMARK_HIDDEN_SIZE = 18
NEURAL_BENCHMARK_CHECKPOINTS_COUNT = 50
NEURAL_BENCHMARK_EPOCHS_PER_CHECKPOINT = 20
NEURAL_BENCHMARK_LEARNING_RATE = 0.04
NEURAL_BENCHMARK_EVALUATION_GAMES_COUNT = 500
NEURAL_BENCHMARK_REFERENCE_EVALUATION_GAMES_COUNT = 200
NEURAL_BENCHMARK_REFERENCE_EVALUATION_OPPONENTS = ["random", "tactical", "greedy"]
NEURAL_BENCHMARK_REFERENCE_TRAINING_GAMES_COUNT = 500
NEURAL_BENCHMARK_REFERENCE_TRAINING_MAX_EXAMPLES = 300
NEURAL_BENCHMARK_REFERENCE_TRAINING_OPPONENTS = ["tactical"]
NEURAL_BENCHMARK_EVALUATION_SEED = 0
NEURAL_BENCHMARK_VALIDATION_RATIO = 0.2
NEURAL_BENCHMARK_EARLY_STOP_PATIENCE = 10


# Dataset Santorini d'inspection, avant entraînement neuronal.
SANTORINI_DATASET_GAMES_COUNT = 50
SANTORINI_DATASET_SIMULATIONS_PER_MOVE = 3
SANTORINI_DATASET_MAX_EXAMPLES = 5
SANTORINI_DATASET_SEED = 0

# Affichage progression.
PROGRESS_BAR_WIDTH = 30
SHOW_PROGRESS_DURING_TRAINING = True